name: CI Docs
on: 
  push:
    paths: 
      - 'src'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Build docs
      run: npm run docs
