name: CI Tests & EsLint
on: 
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm t
    - name: Run eslint
      run: npx eslint .
    - name: Run build
      run: npm run build
